@Teacing api_HostAddress = http://localhost:5099
@Teacing_api_HostAddress = http://localhost:5099


POST {{Teacing_api_HostAddress}}/api/products
Content-Type: application/json

{
"name": "Космический корабль",
  "price": 9999999,
  "categoryId": 102
}

###

GET {{Teacing_api_HostAddress}}/api/products
###

GET {{Teacing_api_HostAddress}}/api/categories

###

GET {{Teacing_api_HostAddress}}/api/categories

###

@id=0
GET {{Teacing_api_HostAddress}}/api/categories/3

###

GET {{Teacing api_HostAddress}}/api/categories

###
