@Teacing api_HostAddress = https://localhost:7166
@Teacing_api_HostAddress = http://localhost:5099



POST {{Teacing_api_HostAddress}}/api/products
Content-Type: application/json

{
    "name": "Книга",
    "price": 500
}

###

GET {{Teacing_api_HostAddress}}/api/products

###
